# Generated by Django 4.2.5 on 2023-09-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(max_length=500, null=True)),
                ('urlToImage', models.URLField(max_length=500, null=True)),
                ('publishedAt', models.DateTimeField(null=True)),
                ('content', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'aticles_db',
            },
        ),
        migrations.CreateModel(
            name='Article_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.CharField(max_length=50, null=True)),
                ('neme', models.CharField(max_length=200, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.articles_db')),
            ],
            options={
                'db_table': 'article_source',
            },
        ),
    ]
