# Generated by Django 4.2.5 on 2023-09-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_source',
            old_name='neme',
            new_name='name',
        ),
    ]
