# Generated by Django 4.2.5 on 2023-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_neme_article_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_db',
            name='key_word',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
