# Generated by Django 4.2.5 on 2023-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_articles_db_key_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_db',
            name='user_search_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
