# Generated by Django 4.2.5 on 2023-09-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_articles_db_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_db',
            name='user_search_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
